name: Create Docs

on: [push]

jobs:
  build-sphinx:
    runs-on: ubuntu-latest
    steps:
      # TODO maybe in the future use reusable workflows or composite workflows
      # for this part here
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: create virtual environment
        run: |
          # python3 -m venv .venv
          python3 -m pip install --upgrade pip
          # source .venv/bin/activate
          python3 -m pip install -r requirements.txt
      
      - name: install cellular_raza
        run: |
          python3 -m pip install .
      # Up until here!

      - name: build cargo documentation in docs dir
        run: |
          cargo doc --no-deps --target-dir docs/build/html/rust_doc

      - name: Install Doc Requirements
        run: |
          python3 -m pip install -r docs/requirements.txt

      # - name: Install latex
        # run: |
        #   python -m pip install latex
        #   sudo apt install texlive texlive-latex-extra texlive-fonts-recommended dvipng cm-super

      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true
